spring.datasource.url=jdbc:postgresql://ambari-node5.csc.calpoly.edu:5432/njc
spring.datasource.username=njc
spring.datasource.password=njc123**

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true